language: node_js
node_js:
  - "0.12"
  - "4"
  - "6"
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database myapp_test;' -U postgres"

